name: homl3
channels:
  - conda-forge
  - defaults
dependencies:
  - box2d-py=2.3  # used only in chapter 18, exercise 8
  - ffmpeg=6.1  # used only in the matplotlib tutorial to generate animations
  - graphviz  # used only in chapter 6 for dot files
  - python-graphviz  # used only in chapter 6 for dot files
  - ipython=8.17  # a powerful Python shell
  - ipywidgets=8.1  # optionally used only in chapter 12 for tqdm in Jupyter
  - joblib=1.3  # used only in chapter 2 to save/load Scikit-Learn models
  - jupyterlab=4.0  # to edit and run Jupyter notebooks
  - matplotlib >= 3.8.2  # beautiful plots. See tutorial tools_matplotlib.ipynb
  - nbdime=3.2  # optional tool to diff Jupyter notebooks
  - nltk=3.8  # optionally used in chapter 3, exercise 4
  - numexpr=2.8  # used only in the Pandas tutorial for numerical expressions
  - numpy ~= 1.25.2  # Powerful n-dimensional arrays and numerical computing tools
  - pandas >= 2.1.4  # data analysis and manipulation tool
  - pillow=10.1  # image manipulation library, (used by matplotlib.image.imread)
  - pip  # Python's package-management system
  - py-xgboost >= 1.7  # used only in chapter 6 for optimized Gradient Boosting
  - pydot=1.4  # used only for in chapter 10 for tf.keras.utils.plot_model()
  - python=3.10  # your beloved programming language! :)
  - requests=2.31  # used only in chapter 19 for REST API queries
  - scikit-learn=1.3  # machine learning library
  - scipy=1.11  # scientific/technical computing library
  - statsmodels=0.14  # used only in chapter 15 for time series analysis
  - tqdm=4.66  # used only in chapter 12 to display nice progress bars
  - wheel  # built-package format for pip
  - widgetsnbextension=4.0  # interactive HTML widgets for Jupyter notebooks
  - pip:
    - keras-core  # used in chapter 10
    - keras-tuner~=1.4.6  # used in chapters 10 and 19 for hyperparameter tuning
    - tensorboard-plugin-profile~=2.14.0  # profiling plugin for TensorBoard
    - tensorboard~=2.14.1  # TensorFlow's visualization toolkit
    - tensorflow-datasets~=4.9.3  # datasets repository, ready to use
    - tensorflow-hub~=0.15.0  # trained ML models repository, ready to use
    - tensorflow-serving-api~=2.14.0  # or tensorflow-serving-api-gpu if gpu
    - tensorflow~=2.14.0  # Deep Learning library
    - transformers~=4.35.0  # Natural Language Processing lib for TF or PyTorch
    - urlextract~=1.8.0  # optionally used in chapter 3, exercise 4
    - gymnasium[classic_control,atari,accept-rom-license]  # used only in ch18
    - google-cloud-aiplatform~=1.36.2  # used only in chapter 19
    - google-cloud-storage~=2.13.0  # used only in chapter 19
    - beartype >= 0.16.4
    - black[jupyter] >= 23.12.0
    - cartopy >= 0.22.0
    - duckdb >= 0.9.2
    - geopandas >= 0.14.1
    - geopy >= 2.4.1
    - hypothesis >= 6.92.1
    - isort >= 5.13.2
    - kaggle >= 1.5.16
    - matplotlib_stubs >= 0.2.0
    - mypy >= 1.7.1
    - nbstripout >= 0.6.1
    - pandas-stubs >= 2.0.3.230814
    - pre-commit >= 3.6.0
    - pyarrow >= 14.0.2
    - pytest-cov >= 4.1.0
    - ruamel.yaml >= 0.18.5
    - ruff >= 0.1.8
    - sqlalchemy_stubs >= 0.4
    - streamlit >= 1.29.0
    - sweetviz >= 2.3.1
    - typer >= 0.9.0
    - types-cachetools >= 5.3.0.7
    - types-colorama >= 0.4.15.12
    - types-decorator >= 5.1.8.4
    - types-jsonschema >= 4.20.0.0
    - types-openpyxl >= 3.1.0.32
    - types-pillow >= 10.1.0.2
    - types-protobuf >= 4.24.0.4
    - types-pygments >= 2.17.0.0
    - types-seaborn >= 0.13.0.8
    - types-six >= 1.16.21.9
    - types-toml >= 0.10.8.7
    - uszipcode >= 1.0.1
    - watchdog >= 3.0.0
    - ydata-profiling >= 4.6.3
